<x-filament-panels::page>
    <div class="documents-ui">
        <style>
            .documents-ui { --surface-border:#e8e2db; --text:#171717; --text-soft:#687384; --orange:#ff5b00; --orange-soft:#fff1e8; --green:#1f9a59; --green-soft:#ebfbf2; --red:#ff3b30; --red-soft:#ffeceb; --purple:#7a49ff; --purple-soft:#f1eafe; --blue:#2e74ff; --blue-soft:#eaf3ff; --pink:#ff4d73; --pink-soft:#ffe8ef; --cyan:#00a3bf; --cyan-soft:#e4f8fb; --gray:#bfc6d2; --gray-soft:#eef1f5; --shadow:0 18px 40px rgba(26,25,31,.06); color:var(--text); font-family:"Plus Jakarta Sans",sans-serif; }
            .documents-ui * { box-sizing:border-box; }
            .documents-ui svg { width:100%; height:100%; stroke:currentColor; stroke-width:1.8; stroke-linecap:round; stroke-linejoin:round; fill:none; }
            .documents-ui button,.documents-ui input { font:inherit; }
            .documents-ui button { border:0; background:none; cursor:pointer; }
            .documents-ui .stats-grid { display:grid; grid-template-columns:repeat(5,minmax(0,1fr)); gap:14px; margin-bottom:16px; }
            .documents-ui .stat-card,.documents-ui .panel,.documents-ui .ghost-button,.documents-ui .primary-button,.documents-ui .icon-button,.documents-ui .page-button,.documents-ui .view-all-button { border:1px solid var(--surface-border); background:rgba(255,255,255,.94); box-shadow:var(--shadow); }
            .documents-ui .stat-card { display:flex; align-items:center; gap:18px; min-height:124px; padding:20px 22px; border-radius:18px; }
            .documents-ui .stat-icon,.documents-ui .doc-icon,.documents-ui .type-icon,.documents-ui .quick-icon { display:grid; place-items:center; width:48px; height:48px; border-radius:14px; flex:0 0 auto; }
            .documents-ui .soft-blue{background:var(--blue-soft);color:var(--blue);} .documents-ui .soft-green{background:var(--green-soft);color:var(--green);} .documents-ui .soft-purple{background:var(--purple-soft);color:var(--purple);} .documents-ui .soft-orange{background:var(--orange-soft);color:var(--orange);} .documents-ui .soft-red{background:var(--red-soft);color:var(--red);}
            .documents-ui .stat-copy span { display:block; margin-bottom:8px; color:#445062; }
            .documents-ui .stat-copy strong { display:block; margin-bottom:8px; font-size:1.95rem; letter-spacing:-.05em; }
            .documents-ui .stat-copy small,.documents-ui .panel-footer { color:var(--text-soft); }
            .documents-ui .main-grid { display:grid; grid-template-columns:minmax(0,1.7fr) 280px; gap:16px; }
            .documents-ui .left-column,.documents-ui .right-column { min-width:0; }
            .documents-ui .right-column { display:grid; gap:16px; align-content:start; }
            .documents-ui .panel { border-radius:22px; overflow:hidden; }
            .documents-ui .panel-toolbar { display:flex; align-items:center; justify-content:space-between; gap:18px; padding:18px 22px 0; }
            .documents-ui .filter-tabs { display:flex; align-items:center; gap:34px; overflow-x:auto; }
            .documents-ui .filter-tab { position:relative; padding:8px 2px 18px; color:#4f5d70; white-space:nowrap; }
            .documents-ui .filter-tab.is-active { color:var(--orange); }
            .documents-ui .filter-tab.is-active::after { content:""; position:absolute; left:0; right:0; bottom:0; height:3px; border-radius:999px; background:var(--orange); }
            .documents-ui .toolbar-actions,.documents-ui .action-cell,.documents-ui .pagination { display:flex; align-items:center; gap:12px; }
            .documents-ui .ghost-button,.documents-ui .primary-button { display:inline-flex; align-items:center; justify-content:center; gap:10px; min-height:34px; padding:0 14px; border-radius:10px; box-shadow:none; white-space:nowrap; }
            .documents-ui .primary-button { background:linear-gradient(180deg,#ff7a2f 0%,var(--orange) 100%); border-color:transparent; color:#fff; }
            .documents-ui .button-icon,.documents-ui .icon-button,.documents-ui .view-all-button svg,.documents-ui .quick-icon svg,.documents-ui .star-button svg { width:18px; height:18px; flex:0 0 auto; }
            .documents-ui .documents-table { padding:0 22px; }
            .documents-ui .documents-grid { display:grid; grid-template-columns:38px minmax(220px,1fr) 108px 126px 132px 84px 90px; gap:12px; align-items:center; }
            .documents-ui .documents-head { padding:18px 0; border-top:1px solid rgba(232,226,219,.85); color:#687384; font-size:.92rem; }
            .documents-ui .documents-row { padding:14px 0; border-top:1px solid rgba(232,226,219,.7); color:#495667; }
            .documents-ui .checkbox-cell { display:inline-flex; align-items:center; justify-content:center; }
            .documents-ui .checkbox-cell input { width:16px; height:16px; accent-color:var(--orange); }
            .documents-ui .doc-main { display:flex; align-items:center; gap:14px; min-width:0; }
            .documents-ui .doc-main strong { display:block; color:#273243; font-weight:500; }
            .documents-ui .doc-main small,.documents-ui .documents-row small { display:block; margin-top:6px; color:#667387; }
            .documents-ui .folder-icon{background:#eaf3ff;color:#5d7193;} .documents-ui .pdf-icon{background:#ffeceb;color:var(--red);} .documents-ui .docx-icon{background:#ebf2ff;color:#3c79ff;} .documents-ui .xlsx-icon{background:#e9f8ec;color:var(--green);} .documents-ui .zip-icon{background:#fff3e2;color:#f39b10;} .documents-ui .ppt-icon{background:#fff2e8;color:#ff7b2e;}
            .documents-ui .small-icon { width:22px; height:22px; border-radius:6px; }
            .documents-ui .tag-pill { display:inline-flex; align-items:center; justify-content:center; min-height:24px; padding:0 8px; border-radius:7px; font-size:.74rem; font-weight:600; white-space:nowrap; }
            .documents-ui .tag-blue{background:#e9f2ff;color:#2e74ff;} .documents-ui .tag-green{background:#e8f8eb;color:#1f9a59;} .documents-ui .tag-pink{background:var(--pink-soft);color:var(--pink);} .documents-ui .tag-purple{background:#efe6ff;color:var(--purple);} .documents-ui .tag-orange{background:#fff0dc;color:#ef8a0c;} .documents-ui .tag-cyan{background:var(--cyan-soft);color:var(--cyan);}
            .documents-ui .star-button,.documents-ui .icon-button { display:inline-flex; align-items:center; justify-content:center; width:36px; height:34px; border-radius:10px; color:#718096; }
            .documents-ui .star-button.is-active { color:var(--orange); }
            .documents-ui .icon-button { box-shadow:none; }
            .documents-ui .panel-footer { display:flex; align-items:center; justify-content:space-between; gap:16px; padding:14px 22px 18px; font-size:.93rem; }
            .documents-ui .page-button { display:inline-flex; align-items:center; justify-content:center; min-width:32px; height:30px; padding:0 8px; border-radius:8px; color:#445062; box-shadow:none; }
            .documents-ui .page-button.is-active { background:var(--orange); color:#fff; border-color:transparent; }
            .documents-ui .storage-panel,.documents-ui .quick-actions-panel,.documents-ui .file-types-panel { padding:18px 20px; }
            .documents-ui .donut-wrap { display:grid; place-items:center; margin:18px 0 20px; }
            .documents-ui .donut-chart { position:relative; width:148px; height:148px; border-radius:50%; background:conic-gradient(var(--blue) 0 24.5%, #d8dde7 24.5% 100%); }
            .documents-ui .donut-chart::after { content:""; position:absolute; inset:18px; border-radius:50%; background:#fff; }
            .documents-ui .donut-center { position:absolute; inset:0; z-index:1; display:grid; place-content:center; text-align:center; }
            .documents-ui .donut-center strong { font-size:1.8rem; letter-spacing:-.05em; }
            .documents-ui .donut-center span { color:var(--text-soft); margin-top:4px; }
            .documents-ui .storage-legend,.documents-ui .type-list,.documents-ui .action-list { display:grid; gap:12px; }
            .documents-ui .legend-row,.documents-ui .type-row { display:grid; grid-template-columns:auto 1fr auto; align-items:center; gap:10px; color:#4a5768; }
            .documents-ui .legend-bullet { width:10px; height:10px; border-radius:50%; }
            .documents-ui .bullet-blue{background:var(--blue);} .documents-ui .bullet-gray{background:#d8dde7;}
            .documents-ui .total-row { grid-template-columns:1fr auto; }
            .documents-ui .quick-action { display:flex; align-items:center; gap:12px; padding:0; color:#314052; text-align:left; }
            .documents-ui .quick-icon { width:18px; height:18px; color:#6a7789; background:transparent; }
            .documents-ui .type-main { display:flex; align-items:center; gap:10px; }
            .documents-ui .view-all-button { display:inline-flex; align-items:center; justify-content:space-between; gap:10px; width:100%; min-height:40px; margin-top:16px; padding:0 14px; border-radius:10px; color:#1767ff; box-shadow:none; }
            @media (max-width:1450px) { .documents-ui .stats-grid{grid-template-columns:repeat(3,minmax(0,1fr));} }
            @media (max-width:1180px) { .documents-ui .main-grid{grid-template-columns:1fr;} .documents-ui .documents-grid,.documents-ui .documents-head{grid-template-columns:1fr;} .documents-ui .documents-head{display:none;} .documents-ui .panel-toolbar{flex-direction:column;align-items:stretch;} .documents-ui .toolbar-actions{justify-content:flex-end;} }
            @media (max-width:760px) { .documents-ui .stats-grid{grid-template-columns:1fr;} .documents-ui .toolbar-actions{flex-direction:column;} .documents-ui .ghost-button,.documents-ui .primary-button{width:100%;} .documents-ui .panel-footer{flex-direction:column;align-items:flex-start;} }
        </style>

        <section class="stats-grid" aria-label="Document summary">
            <article class="stat-card"><div class="stat-icon soft-blue"><svg viewBox="0 0 24 24"><path d="M4.5 6.5A1.5 1.5 0 0 1 6 5h4l1.5 2h6.5A1.5 1.5 0 0 1 19.5 8.5v8A1.5 1.5 0 0 1 18 18H6a1.5 1.5 0 0 1-1.5-1.5Z"/></svg></div><div class="stat-copy"><span>Total Documents</span><strong>68</strong><small>All time</small></div></article>
            <article class="stat-card"><div class="stat-icon soft-green"><svg viewBox="0 0 24 24"><path d="M12 16V7"/><path d="m8.5 10.5 3.5-3.5 3.5 3.5"/><path d="M7 18.5h10a3.5 3.5 0 0 0 .3-7A5.5 5.5 0 0 0 7 11.8 3.3 3.3 0 0 0 7 18.5Z"/></svg></div><div class="stat-copy"><span>Uploaded Documents</span><strong>42</strong><small>This year</small></div></article>
            <article class="stat-card"><div class="stat-icon soft-purple"><svg viewBox="0 0 24 24"><path d="M12 7v9"/><path d="m8.5 12.5 3.5 3.5 3.5-3.5"/><path d="M5 19h14"/></svg></div><div class="stat-copy"><span>Downloaded Documents</span><strong>26</strong><small>This year</small></div></article>
            <article class="stat-card"><div class="stat-icon soft-orange"><svg viewBox="0 0 24 24"><path d="M4.5 6.5A1.5 1.5 0 0 1 6 5h4l1.5 2h6.5A1.5 1.5 0 0 1 19.5 8.5v8A1.5 1.5 0 0 1 18 18H6a1.5 1.5 0 0 1-1.5-1.5Z"/></svg></div><div class="stat-copy"><span>Storage Used</span><strong>2.45 GB</strong><small>of 10 GB</small></div></article>
            <article class="stat-card"><div class="stat-icon soft-red"><svg viewBox="0 0 24 24"><path d="M6 3.5h8l4 4V20a1.5 1.5 0 0 1-1.5 1.5h-10A1.5 1.5 0 0 1 5 20V5A1.5 1.5 0 0 1 6.5 3.5Z"/><path d="M14 3.5V8h4"/><path d="M9 14h6"/><path d="M9 17h4"/></svg></div><div class="stat-copy"><span>Folders</span><strong>12</strong><small>Total folders</small></div></article>
        </section>

        <section class="main-grid">
            <div class="left-column">
                <section class="panel documents-panel">
                    <div class="panel-toolbar">
                        <div class="filter-tabs"><button type="button" class="filter-tab is-active">All Documents</button><button type="button" class="filter-tab">Recently Uploaded</button><button type="button" class="filter-tab">Shared with Me</button><button type="button" class="filter-tab">Favorites</button></div>
                        <div class="toolbar-actions"><button type="button" class="ghost-button"><span class="button-icon"><svg viewBox="0 0 24 24"><path d="M4 6h16"/><path d="M7 12h10"/><path d="M10 18h4"/></svg></span><span>Filter</span></button><button type="button" class="primary-button"><span class="button-icon"><svg viewBox="0 0 24 24"><path d="M12 5v14"/><path d="M5 12h14"/></svg></span><span>Upload Document</span></button></div>
                    </div>
                    <div class="documents-table">
                        <div class="documents-head documents-grid"><span class="checkbox-cell"><input type="checkbox" aria-label="Select all documents"></span><span>Document Name</span><span>Category</span><span>Uploaded By</span><span>Uploaded On</span><span>Size</span><span>Actions</span></div>
                        <div class="documents-row documents-grid"><span class="checkbox-cell"><input type="checkbox" aria-label="Select Project Proposals"></span><div class="doc-main"><span class="doc-icon folder-icon"><svg viewBox="0 0 24 24"><path d="M4.5 6.5A1.5 1.5 0 0 1 6 5h4l1.5 2h6.5A1.5 1.5 0 0 1 19.5 8.5v8A1.5 1.5 0 0 1 18 18H6a1.5 1.5 0 0 1-1.5-1.5Z"/></svg></span><div><strong>Project Proposals</strong><small>12 documents</small></div></div><span><b class="tag-pill tag-blue">Project</b></span><span>Acme Ltd</span><span>May 15, 2025<br><small>10:30 AM</small></span><span>--</span><span class="action-cell"><button type="button" class="star-button" aria-label="Favorite"><svg viewBox="0 0 24 24"><path d="m12 4 2.5 5 5.5.8-4 3.9.9 5.5-4.9-2.6-4.9 2.6.9-5.5-4-3.9 5.5-.8Z"/></svg></button><button type="button" class="icon-button" aria-label="More actions"><svg viewBox="0 0 24 24"><path d="M12 6h.01"/><path d="M12 12h.01"/><path d="M12 18h.01"/></svg></button></span></div>
                        <div class="documents-row documents-grid"><span class="checkbox-cell"><input type="checkbox" aria-label="Select Brand Guidelines PDF"></span><div class="doc-main"><span class="doc-icon pdf-icon"><svg viewBox="0 0 24 24"><path d="M6 3.5h8l4 4V20a1.5 1.5 0 0 1-1.5 1.5h-10A1.5 1.5 0 0 1 5 20V5A1.5 1.5 0 0 1 6.5 3.5Z"/><path d="M14 3.5V8h4"/><path d="M8 16h8"/><path d="M8 12h5"/></svg></span><div><strong>Brand Guidelines.pdf</strong></div></div><span><b class="tag-pill tag-purple">Design</b></span><span>Acme Ltd</span><span>May 13, 2025<br><small>12:05 PM</small></span><span>3.2 MB</span><span class="action-cell"><button type="button" class="star-button is-active" aria-label="Favorite"><svg viewBox="0 0 24 24"><path d="m12 4 2.5 5 5.5.8-4 3.9.9 5.5-4.9-2.6-4.9 2.6.9-5.5-4-3.9 5.5-.8Z"/></svg></button><button type="button" class="icon-button" aria-label="More actions"><svg viewBox="0 0 24 24"><path d="M12 6h.01"/><path d="M12 12h.01"/><path d="M12 18h.01"/></svg></button></span></div>
                        <div class="documents-row documents-grid"><span class="checkbox-cell"><input type="checkbox" aria-label="Select Hosting Setup Guide PDF"></span><div class="doc-main"><span class="doc-icon pdf-icon"><svg viewBox="0 0 24 24"><path d="M6 3.5h8l4 4V20a1.5 1.5 0 0 1-1.5 1.5h-10A1.5 1.5 0 0 1 5 20V5A1.5 1.5 0 0 1 6.5 3.5Z"/><path d="M14 3.5V8h4"/><path d="M8 16h8"/><path d="M8 12h5"/></svg></span><div><strong>Hosting Setup Guide.pdf</strong></div></div><span><b class="tag-pill tag-cyan">Hosting</b></span><span>i2Medier</span><span>May 11, 2025<br><small>04:15 PM</small></span><span>2.1 MB</span><span class="action-cell"><button type="button" class="star-button" aria-label="Favorite"><svg viewBox="0 0 24 24"><path d="m12 4 2.5 5 5.5.8-4 3.9.9 5.5-4.9-2.6-4.9 2.6.9-5.5-4-3.9 5.5-.8Z"/></svg></button><button type="button" class="icon-button" aria-label="More actions"><svg viewBox="0 0 24 24"><path d="M12 6h.01"/><path d="M12 12h.01"/><path d="M12 18h.01"/></svg></button></span></div>
                        <div class="documents-row documents-grid"><span class="checkbox-cell"><input type="checkbox" aria-label="Select Monthly Report"></span><div class="doc-main"><span class="doc-icon xlsx-icon"><svg viewBox="0 0 24 24"><path d="M6 3.5h8l4 4V20a1.5 1.5 0 0 1-1.5 1.5h-10A1.5 1.5 0 0 1 5 20V5A1.5 1.5 0 0 1 6.5 3.5Z"/><path d="M14 3.5V8h4"/><path d="m8.5 16 4-5"/><path d="m8.5 11 4 5"/></svg></span><div><strong>Monthly Report - April 2025.xlsx</strong></div></div><span><b class="tag-pill tag-green">Reports</b></span><span>Acme Ltd</span><span>May 8, 2025<br><small>01:15 PM</small></span><span>834 KB</span><span class="action-cell"><button type="button" class="star-button is-active" aria-label="Favorite"><svg viewBox="0 0 24 24"><path d="m12 4 2.5 5 5.5.8-4 3.9.9 5.5-4.9-2.6-4.9 2.6.9-5.5-4-3.9 5.5-.8Z"/></svg></button><button type="button" class="icon-button" aria-label="More actions"><svg viewBox="0 0 24 24"><path d="M12 6h.01"/><path d="M12 12h.01"/><path d="M12 18h.01"/></svg></button></span></div>
                        <div class="documents-row documents-grid"><span class="checkbox-cell"><input type="checkbox" aria-label="Select Logos and Brand Assets"></span><div class="doc-main"><span class="doc-icon folder-icon"><svg viewBox="0 0 24 24"><path d="M4.5 6.5A1.5 1.5 0 0 1 6 5h4l1.5 2h6.5A1.5 1.5 0 0 1 19.5 8.5v8A1.5 1.5 0 0 1 18 18H6a1.5 1.5 0 0 1-1.5-1.5Z"/></svg></span><div><strong>Logos &amp; Brand Assets</strong><small>8 documents</small></div></div><span><b class="tag-pill tag-purple">Design</b></span><span>Acme Ltd</span><span>May 5, 2025<br><small>10:05 AM</small></span><span>--</span><span class="action-cell"><button type="button" class="star-button" aria-label="Favorite"><svg viewBox="0 0 24 24"><path d="m12 4 2.5 5 5.5.8-4 3.9.9 5.5-4.9-2.6-4.9 2.6.9-5.5-4-3.9 5.5-.8Z"/></svg></button><button type="button" class="icon-button" aria-label="More actions"><svg viewBox="0 0 24 24"><path d="M12 6h.01"/><path d="M12 12h.01"/><path d="M12 18h.01"/></svg></button></span></div>
                        <div class="documents-row documents-grid"><span class="checkbox-cell"><input type="checkbox" aria-label="Select Project Presentation"></span><div class="doc-main"><span class="doc-icon ppt-icon"><svg viewBox="0 0 24 24"><path d="M6 3.5h8l4 4V20a1.5 1.5 0 0 1-1.5 1.5h-10A1.5 1.5 0 0 1 5 20V5A1.5 1.5 0 0 1 6.5 3.5Z"/><path d="M14 3.5V8h4"/><path d="M8 12h6"/><path d="M8 16h4"/></svg></span><div><strong>Project Presentation.pptx</strong></div></div><span><b class="tag-pill tag-orange">Presentation</b></span><span>Acme Ltd</span><span>May 3, 2025<br><small>05:20 PM</small></span><span>5.4 MB</span><span class="action-cell"><button type="button" class="star-button" aria-label="Favorite"><svg viewBox="0 0 24 24"><path d="m12 4 2.5 5 5.5.8-4 3.9.9 5.5-4.9-2.6-4.9 2.6.9-5.5-4-3.9 5.5-.8Z"/></svg></button><button type="button" class="icon-button" aria-label="More actions"><svg viewBox="0 0 24 24"><path d="M12 6h.01"/><path d="M12 12h.01"/><path d="M12 18h.01"/></svg></button></span></div>
                        <div class="documents-row documents-grid"><span class="checkbox-cell"><input type="checkbox" aria-label="Select SSL Certificate"></span><div class="doc-main"><span class="doc-icon pdf-icon"><svg viewBox="0 0 24 24"><path d="M6 3.5h8l4 4V20a1.5 1.5 0 0 1-1.5 1.5h-10A1.5 1.5 0 0 1 5 20V5A1.5 1.5 0 0 1 6.5 3.5Z"/><path d="M14 3.5V8h4"/><path d="M8 16h8"/><path d="M8 12h5"/></svg></span><div><strong>SSL Certificate (acme.com).pdf</strong></div></div><span><b class="tag-pill tag-cyan">Certificates</b></span><span>Acme Ltd</span><span>Apr 30, 2025<br><small>04:50 PM</small></span><span>380 KB</span><span class="action-cell"><button type="button" class="star-button" aria-label="Favorite"><svg viewBox="0 0 24 24"><path d="m12 4 2.5 5 5.5.8-4 3.9.9 5.5-4.9-2.6-4.9 2.6.9-5.5-4-3.9 5.5-.8Z"/></svg></button><button type="button" class="icon-button" aria-label="More actions"><svg viewBox="0 0 24 24"><path d="M12 6h.01"/><path d="M12 12h.01"/><path d="M12 18h.01"/></svg></button></span></div>
                    </div>
                    <div class="panel-footer"><span>Showing 1 to 10 of 68 documents</span><div class="pagination"><button type="button" class="page-button" aria-label="Previous page"><svg viewBox="0 0 24 24"><path d="m14 7-5 5 5 5"/></svg></button><button type="button" class="page-button is-active">1</button><button type="button" class="page-button">2</button><button type="button" class="page-button">3</button><button type="button" class="page-button">...</button><button type="button" class="page-button">7</button><button type="button" class="page-button" aria-label="Next page"><svg viewBox="0 0 24 24"><path d="m10 7 5 5-5 5"/></svg></button></div></div>
                </section>
            </div>

            <aside class="right-column">
                <section class="panel storage-panel"><h2>Storage Overview</h2><div class="donut-wrap"><div class="donut-chart" aria-hidden="true"><div class="donut-center"><strong>2.45 GB</strong><span>Used</span></div></div></div><div class="storage-legend"><div class="legend-row"><span class="legend-bullet bullet-blue"></span><span>Documents</span><strong>2.45 GB</strong></div><div class="legend-row"><span class="legend-bullet bullet-gray"></span><span>Available</span><strong>7.55 GB</strong></div><div class="legend-row total-row"><span>Total</span><strong>10 GB</strong></div></div></section>
                <section class="panel quick-actions-panel"><h2>Quick Actions</h2><div class="action-list"><button type="button" class="quick-action"><span class="quick-icon"><svg viewBox="0 0 24 24"><path d="M12 16V7"/><path d="m8.5 10.5 3.5-3.5 3.5 3.5"/><path d="M7 18.5h10a3.5 3.5 0 0 0 .3-7A5.5 5.5 0 0 0 7 11.8 3.3 3.3 0 0 0 7 18.5Z"/></svg></span><span>Upload Document</span></button><button type="button" class="quick-action"><span class="quick-icon"><svg viewBox="0 0 24 24"><path d="M4.5 6.5A1.5 1.5 0 0 1 6 5h4l1.5 2h6.5A1.5 1.5 0 0 1 19.5 8.5v8A1.5 1.5 0 0 1 18 18H6a1.5 1.5 0 0 1-1.5-1.5Z"/><path d="M12 10v5"/><path d="M9.5 12.5h5"/></svg></span><span>Create New Folder</span></button><button type="button" class="quick-action"><span class="quick-icon"><svg viewBox="0 0 24 24"><circle cx="18" cy="5" r="2"/><circle cx="6" cy="12" r="2"/><circle cx="18" cy="19" r="2"/><path d="m7.7 11 8.5-4.8"/><path d="m7.7 13 8.5 4.8"/></svg></span><span>Share a Document</span></button><button type="button" class="quick-action"><span class="quick-icon"><svg viewBox="0 0 24 24"><path d="M12 7v9"/><path d="m8.5 12.5 3.5 3.5 3.5-3.5"/><path d="M5 19h14"/></svg></span><span>Request a Document</span></button></div></section>
                <section class="panel file-types-panel"><h2>File Types</h2><div class="type-list"><div class="type-row"><div class="type-main"><span class="type-icon pdf-icon small-icon"><svg viewBox="0 0 24 24"><path d="M6 3.5h8l4 4V20a1.5 1.5 0 0 1-1.5 1.5h-10A1.5 1.5 0 0 1 5 20V5A1.5 1.5 0 0 1 6.5 3.5Z"/><path d="M14 3.5V8h4"/><path d="M8 16h8"/><path d="M8 12h5"/></svg></span><span>PDF Documents</span></div><strong>22</strong></div><div class="type-row"><div class="type-main"><span class="type-icon docx-icon small-icon"><svg viewBox="0 0 24 24"><path d="M6 3.5h8l4 4V20a1.5 1.5 0 0 1-1.5 1.5h-10A1.5 1.5 0 0 1 5 20V5A1.5 1.5 0 0 1 6.5 3.5Z"/><path d="M14 3.5V8h4"/><rect x="8" y="10.5" width="5" height="6" rx="1"/></svg></span><span>Word Documents</span></div><strong>15</strong></div><div class="type-row"><div class="type-main"><span class="type-icon xlsx-icon small-icon"><svg viewBox="0 0 24 24"><path d="M6 3.5h8l4 4V20a1.5 1.5 0 0 1-1.5 1.5h-10A1.5 1.5 0 0 1 5 20V5A1.5 1.5 0 0 1 6.5 3.5Z"/><path d="M14 3.5V8h4"/><path d="m8.5 16 4-5"/><path d="m8.5 11 4 5"/></svg></span><span>Excel Sheets</span></div><strong>8</strong></div><div class="type-row"><div class="type-main"><span class="type-icon zip-icon small-icon"><svg viewBox="0 0 24 24"><path d="M6 3.5h8l4 4V20a1.5 1.5 0 0 1-1.5 1.5h-10A1.5 1.5 0 0 1 5 20V5A1.5 1.5 0 0 1 6.5 3.5Z"/><path d="M14 3.5V8h4"/><path d="M10 9h2"/><path d="M10 12h2"/><path d="M10 15h2"/></svg></span><span>Images</span></div><strong>12</strong></div><div class="type-row"><div class="type-main"><span class="type-icon folder-icon small-icon"><svg viewBox="0 0 24 24"><path d="M4.5 6.5A1.5 1.5 0 0 1 6 5h4l1.5 2h6.5A1.5 1.5 0 0 1 19.5 8.5v8A1.5 1.5 0 0 1 18 18H6a1.5 1.5 0 0 1-1.5-1.5Z"/></svg></span><span>Other Files</span></div><strong>11</strong></div></div><button type="button" class="view-all-button"><span>View all</span><svg viewBox="0 0 24 24"><path d="m10 7 5 5-5 5"/></svg></button></section>
            </aside>
        </section>
    </div>
</x-filament-panels::page>
