<x-filament-panels::page>
    <div class="subscriptions-ui">
        <style>
            .subscriptions-ui { --surface-border:#e8e2db; --text:#171717; --text-soft:#687384; --orange:#ff5b00; --orange-soft:#fff1e8; --green:#1f9a59; --green-soft:#ebfbf2; --red:#ff3b30; --red-soft:#ffeceb; --purple:#7a49ff; --purple-soft:#f1eafe; --blue:#2e74ff; --blue-soft:#eaf3ff; --slate:#667085; --slate-soft:#eef1f5; --shadow:0 18px 40px rgba(26,25,31,.06); color:var(--text); font-family:"Plus Jakarta Sans",sans-serif; }
            .subscriptions-ui * { box-sizing:border-box; }
            .subscriptions-ui svg { width:100%; height:100%; stroke:currentColor; stroke-width:1.8; stroke-linecap:round; stroke-linejoin:round; fill:none; }
            .subscriptions-ui button { border:0; background:none; cursor:pointer; font:inherit; }
            .subscriptions-ui .stats-grid { display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:14px; margin-bottom:18px; }
            .subscriptions-ui .stat-card,.subscriptions-ui .panel,.subscriptions-ui .ghost-button,.subscriptions-ui .manage-button,.subscriptions-ui .icon-button,.subscriptions-ui .primary-button { border:1px solid var(--surface-border); background:rgba(255,255,255,.94); box-shadow:var(--shadow); }
            .subscriptions-ui .stat-card { display:flex; align-items:center; gap:18px; min-height:124px; padding:20px 24px; border-radius:18px; }
            .subscriptions-ui .stat-icon,.subscriptions-ui .info-icon,.subscriptions-ui .row-icon { display:grid; place-items:center; width:48px; height:48px; border-radius:14px; flex:0 0 auto; }
            .subscriptions-ui .soft-purple{background:var(--purple-soft);color:var(--purple);} .subscriptions-ui .soft-green{background:var(--green-soft);color:var(--green);} .subscriptions-ui .soft-orange{background:var(--orange-soft);color:var(--orange);} .subscriptions-ui .soft-red{background:var(--red-soft);color:var(--red);} .subscriptions-ui .soft-blue{background:var(--blue-soft);color:var(--blue);} .subscriptions-ui .soft-slate{background:var(--slate-soft);color:var(--slate);}
            .subscriptions-ui .stat-copy span { display:block; margin-bottom:8px; color:#445062; }
            .subscriptions-ui .stat-copy strong { display:block; margin-bottom:8px; font-size:1.95rem; letter-spacing:-.05em; }
            .subscriptions-ui .stat-copy small,.subscriptions-ui .panel-footnote,.subscriptions-ui .info-copy p { color:var(--text-soft); }
            .subscriptions-ui .panel { border-radius:22px; overflow:hidden; }
            .subscriptions-ui .subscriptions-panel { padding-bottom:14px; }
            .subscriptions-ui .panel-toolbar { display:flex; align-items:center; justify-content:space-between; gap:18px; padding:18px 22px 0; }
            .subscriptions-ui .filter-tabs { display:flex; align-items:center; gap:34px; overflow-x:auto; }
            .subscriptions-ui .filter-tab { position:relative; padding:8px 2px 18px; color:#4f5d70; white-space:nowrap; }
            .subscriptions-ui .filter-tab.is-active { color:var(--orange); }
            .subscriptions-ui .filter-tab.is-active::after { content:""; position:absolute; left:0; right:0; bottom:0; height:3px; border-radius:999px; background:var(--orange); }
            .subscriptions-ui .toolbar-actions,.subscriptions-ui .action-cell { display:flex; align-items:center; gap:12px; }
            .subscriptions-ui .ghost-button,.subscriptions-ui .primary-button,.subscriptions-ui .manage-button { display:inline-flex; align-items:center; justify-content:center; gap:10px; min-height:34px; padding:0 14px; border-radius:10px; box-shadow:none; white-space:nowrap; }
            .subscriptions-ui .primary-button { background:linear-gradient(180deg,#ff7a2f 0%,var(--orange) 100%); border-color:transparent; color:#fff; }
            .subscriptions-ui .button-icon,.subscriptions-ui .icon-button { width:18px; height:18px; flex:0 0 auto; }
            .subscriptions-ui .subscription-table { padding:0 22px; }
            .subscriptions-ui .subscription-grid { display:grid; grid-template-columns:250px 140px 168px 110px 150px 130px 118px; gap:12px; align-items:center; }
            .subscriptions-ui .subscription-head { padding:18px 0; border-top:1px solid rgba(232,226,219,.85); color:#687384; font-size:.92rem; }
            .subscriptions-ui .subscription-row { padding:14px 0; border-top:1px solid rgba(232,226,219,.7); }
            .subscriptions-ui .subscription-cell { color:#495667; }
            .subscriptions-ui .subscription-cell strong { display:block; color:#273243; font-weight:500; }
            .subscriptions-ui .subscription-cell small { display:block; margin-top:6px; color:#667387; }
            .subscriptions-ui .subscription-main { display:flex; align-items:center; gap:14px; }
            .subscriptions-ui .status-pill { display:inline-flex; align-items:center; justify-content:center; min-height:26px; padding:0 10px; border-radius:8px; font-size:.75rem; font-weight:600; white-space:nowrap; }
            .subscriptions-ui .pill-green{background:#e7f8ec;color:var(--green);} .subscriptions-ui .pill-amber{background:#fff0d8;color:#da8400;} .subscriptions-ui .pill-red{background:#ffe8e7;color:var(--red);}
            .subscriptions-ui .due-soon { color:var(--orange)!important; font-weight:500; }
            .subscriptions-ui .icon-button { display:inline-flex; align-items:center; justify-content:center; width:36px; height:34px; border-radius:10px; color:#556274; box-shadow:none; }
            .subscriptions-ui .panel-footnote { margin:12px 22px 0; font-size:.93rem; }
            .subscriptions-ui .info-grid { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:14px; margin-top:14px; }
            .subscriptions-ui .info-card { display:flex; align-items:flex-start; gap:18px; padding:18px 20px; min-height:134px; }
            .subscriptions-ui .info-copy p { margin:12px 0 16px; line-height:1.55; }
            .subscriptions-ui .compact { min-height:34px; }
            @media (max-width:1400px) { .subscriptions-ui .stats-grid{grid-template-columns:repeat(2,minmax(0,1fr));} .subscriptions-ui .info-grid{grid-template-columns:1fr;} }
            @media (max-width:1180px) { .subscriptions-ui .subscription-grid,.subscriptions-ui .subscription-head{grid-template-columns:1fr;} .subscriptions-ui .subscription-head{display:none;} .subscriptions-ui .panel-toolbar{flex-direction:column;align-items:stretch;} .subscriptions-ui .toolbar-actions{justify-content:flex-end;} }
            @media (max-width:760px) { .subscriptions-ui .stats-grid{grid-template-columns:1fr;} .subscriptions-ui .toolbar-actions{justify-content:stretch;flex-direction:column;} .subscriptions-ui .ghost-button,.subscriptions-ui .primary-button{width:100%;} .subscriptions-ui .info-card{flex-direction:column;} }
        </style>

        <section class="stats-grid" aria-label="Subscription summary">
            <article class="stat-card"><div class="stat-icon soft-purple"><svg viewBox="0 0 24 24"><path d="M12 4 4.5 8 12 12 19.5 8 12 4Z"/><path d="M4.5 12 12 16l7.5-4"/><path d="M4.5 16 12 20l7.5-4"/></svg></div><div class="stat-copy"><span>Total Subscriptions</span><strong>7</strong><small>All subscriptions</small></div></article>
            <article class="stat-card"><div class="stat-icon soft-green"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8"/><path d="m8.5 12 2.2 2.2 4.8-5"/></svg></div><div class="stat-copy"><span>Active</span><strong>5</strong><small>71.4% of total</small></div></article>
            <article class="stat-card"><div class="stat-icon soft-orange"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8"/><path d="M12 8v4.5l2.5 1.5"/></svg></div><div class="stat-copy"><span>Expiring Soon</span><strong>1</strong><small>14.3% of total</small></div></article>
            <article class="stat-card"><div class="stat-icon soft-red"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8"/><path d="m9 9 6 6"/><path d="m15 9-6 6"/></svg></div><div class="stat-copy"><span>Cancelled</span><strong>1</strong><small>14.3% of total</small></div></article>
        </section>

        <section class="panel subscriptions-panel">
            <div class="panel-toolbar">
                <div class="filter-tabs"><button type="button" class="filter-tab is-active">All Subscriptions</button><button type="button" class="filter-tab">Active</button><button type="button" class="filter-tab">Expiring Soon</button><button type="button" class="filter-tab">Cancelled</button></div>
                <div class="toolbar-actions"><button type="button" class="ghost-button"><span class="button-icon"><svg viewBox="0 0 24 24"><path d="M4 6h16"/><path d="M7 12h10"/><path d="M10 18h4"/></svg></span><span>Filter</span></button><button type="button" class="primary-button"><span class="button-icon"><svg viewBox="0 0 24 24"><path d="M12 5v14"/><path d="M5 12h14"/></svg></span><span>New Subscription</span></button></div>
            </div>

            <div class="subscription-table">
                <div class="subscription-head subscription-grid"><span>Subscription</span><span>Service</span><span>Plan</span><span>Status</span><span>Next Billing Date</span><span>Amount / Cycle</span><span>Actions</span></div>
                <div class="subscription-row subscription-grid"><div class="subscription-cell subscription-main"><span class="row-icon soft-purple"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8"/><path d="M3.5 12h17"/><path d="M12 4a12 12 0 0 1 3 8 12 12 0 0 1-3 8 12 12 0 0 1-3-8 12 12 0 0 1 3-8Z"/></svg></span><div><strong>Domain Subscription</strong><small>#SUB-0001</small></div></div><div class="subscription-cell"><strong>acme.com</strong><small>Domain</small></div><div class="subscription-cell"><strong>Domain Registration</strong></div><div class="subscription-cell"><b class="status-pill pill-green">Active</b></div><div class="subscription-cell"><strong>May 15, 2025</strong><small class="due-soon">23 days left</small></div><div class="subscription-cell"><strong>₦8,000</strong><small>1 Year</small></div><div class="subscription-cell action-cell"><button type="button" class="manage-button">Manage</button><button type="button" class="icon-button" aria-label="More actions"><svg viewBox="0 0 24 24"><path d="M12 6h.01"/><path d="M12 12h.01"/><path d="M12 18h.01"/></svg></button></div></div>
                <div class="subscription-row subscription-grid"><div class="subscription-cell subscription-main"><span class="row-icon soft-blue"><svg viewBox="0 0 24 24"><rect x="4.5" y="6" width="15" height="5" rx="1.5"/><rect x="4.5" y="13" width="15" height="5" rx="1.5"/><path d="M8 8.5h.01"/><path d="M8 15.5h.01"/></svg></span><div><strong>Premium Hosting</strong><small>#SUB-0002</small></div></div><div class="subscription-cell"><strong>acme.net</strong><small>Hosting</small></div><div class="subscription-cell"><strong>Premium Hosting</strong></div><div class="subscription-cell"><b class="status-pill pill-green">Active</b></div><div class="subscription-cell"><strong>May 20, 2025</strong><small class="due-soon">28 days left</small></div><div class="subscription-cell"><strong>₦90,000</strong><small>1 Year</small></div><div class="subscription-cell action-cell"><button type="button" class="manage-button">Manage</button><button type="button" class="icon-button" aria-label="More actions"><svg viewBox="0 0 24 24"><path d="M12 6h.01"/><path d="M12 12h.01"/><path d="M12 18h.01"/></svg></button></div></div>
                <div class="subscription-row subscription-grid"><div class="subscription-cell subscription-main"><span class="row-icon soft-green"><svg viewBox="0 0 24 24"><path d="M12 3.5 6 6v5c0 4.2 2.5 7 6 9.5 3.5-2.5 6-5.3 6-9.5V6l-6-2.5Z"/><path d="m9.2 11.7 1.9 1.9 3.7-4"/></svg></span><div><strong>SSL Certificate</strong><small>#SUB-0003</small></div></div><div class="subscription-cell"><strong>acme.com</strong><small>SSL</small></div><div class="subscription-cell"><strong>RapidSSL</strong></div><div class="subscription-cell"><b class="status-pill pill-green">Active</b></div><div class="subscription-cell"><strong>Jun 10, 2025</strong><small class="due-soon">49 days left</small></div><div class="subscription-cell"><strong>₦15,000</strong><small>1 Year</small></div><div class="subscription-cell action-cell"><button type="button" class="manage-button">Manage</button><button type="button" class="icon-button" aria-label="More actions"><svg viewBox="0 0 24 24"><path d="M12 6h.01"/><path d="M12 12h.01"/><path d="M12 18h.01"/></svg></button></div></div>
                <div class="subscription-row subscription-grid"><div class="subscription-cell subscription-main"><span class="row-icon soft-red"><svg viewBox="0 0 24 24"><path d="M4.5 7.5h15v9h-15Z"/><path d="m5.5 8.5 6.5 5 6.5-5"/></svg></span><div><strong>Business Email</strong><small>#SUB-0004</small></div></div><div class="subscription-cell"><strong>5 Mailboxes</strong><small>Email</small></div><div class="subscription-cell"><strong>Business Email</strong></div><div class="subscription-cell"><b class="status-pill pill-green">Active</b></div><div class="subscription-cell"><strong>May 25, 2025</strong><small class="due-soon">33 days left</small></div><div class="subscription-cell"><strong>₦24,000</strong><small>1 Year</small></div><div class="subscription-cell action-cell"><button type="button" class="manage-button">Manage</button><button type="button" class="icon-button" aria-label="More actions"><svg viewBox="0 0 24 24"><path d="M12 6h.01"/><path d="M12 12h.01"/><path d="M12 18h.01"/></svg></button></div></div>
                <div class="subscription-row subscription-grid"><div class="subscription-cell subscription-main"><span class="row-icon soft-purple"><svg viewBox="0 0 24 24"><path d="M7 14.5A5 5 0 0 1 8.5 5 4.5 4.5 0 0 1 17 6.8 4 4 0 0 1 16.5 14.5H7Z"/><path d="M12 10v8"/><path d="m9.5 15 2.5 3 2.5-3"/></svg></span><div><strong>Daily Backup</strong><small>#SUB-0005</small></div></div><div class="subscription-cell"><strong>acme.net</strong><small>Backup</small></div><div class="subscription-cell"><strong>Daily Backup</strong></div><div class="subscription-cell"><b class="status-pill pill-green">Active</b></div><div class="subscription-cell"><strong>May 20, 2025</strong><small class="due-soon">28 days left</small></div><div class="subscription-cell"><strong>₦10,000</strong><small>1 Year</small></div><div class="subscription-cell action-cell"><button type="button" class="manage-button">Manage</button><button type="button" class="icon-button" aria-label="More actions"><svg viewBox="0 0 24 24"><path d="M12 6h.01"/><path d="M12 12h.01"/><path d="M12 18h.01"/></svg></button></div></div>
                <div class="subscription-row subscription-grid"><div class="subscription-cell subscription-main"><span class="row-icon soft-orange"><svg viewBox="0 0 24 24"><path d="M3.5 12h6l2 2h9"/><path d="M7 14.5V17"/><path d="M7 7v2.5"/><path d="M12 9 20.5 5v10L12 11"/></svg></span><div><strong>Website Maintenance</strong><small>#SUB-0006</small></div></div><div class="subscription-cell"><strong>acme.com</strong><small>Maintenance</small></div><div class="subscription-cell"><strong>Standard Maintenance</strong></div><div class="subscription-cell"><b class="status-pill pill-amber">Expiring Soon</b></div><div class="subscription-cell"><strong>Jun 12, 2025</strong><small class="due-soon">51 days left</small></div><div class="subscription-cell"><strong>₦30,000</strong><small>1 Year</small></div><div class="subscription-cell action-cell"><button type="button" class="manage-button">Manage</button><button type="button" class="icon-button" aria-label="More actions"><svg viewBox="0 0 24 24"><path d="M12 6h.01"/><path d="M12 12h.01"/><path d="M12 18h.01"/></svg></button></div></div>
                <div class="subscription-row subscription-grid"><div class="subscription-cell subscription-main"><span class="row-icon soft-slate"><svg viewBox="0 0 24 24"><rect x="4.5" y="6" width="15" height="5" rx="1.5"/><rect x="4.5" y="13" width="15" height="5" rx="1.5"/><path d="M8 8.5h.01"/><path d="M8 15.5h.01"/></svg></span><div><strong>Old Hosting Plan</strong><small>#SUB-0007</small></div></div><div class="subscription-cell"><strong>acme.org</strong><small>Hosting</small></div><div class="subscription-cell"><strong>Basic Hosting</strong></div><div class="subscription-cell"><b class="status-pill pill-red">Cancelled</b></div><div class="subscription-cell"><strong>Apr 10, 2025</strong><small>-</small></div><div class="subscription-cell"><strong>₦50,000</strong><small>1 Year</small></div><div class="subscription-cell action-cell"><button type="button" class="manage-button">Manage</button><button type="button" class="icon-button" aria-label="More actions"><svg viewBox="0 0 24 24"><path d="M12 6h.01"/><path d="M12 12h.01"/><path d="M12 18h.01"/></svg></button></div></div>
            </div>
            <p class="panel-footnote">Showing 1 to 7 of 7 subscriptions</p>
        </section>

        <section class="info-grid">
            <article class="panel info-card"><div class="info-icon soft-blue"><svg viewBox="0 0 24 24"><path d="M12 4.5a7.5 7.5 0 1 0 7.5 7.5"/><path d="M12 1.5v4"/><path d="m20 4-2.5 2.5"/><path d="M12 19.5v3"/><path d="M4 20l2.5-2.5"/></svg></div><div class="info-copy"><h2>Auto Renewal</h2><p>All active subscriptions are set to auto renew. You will be notified before renewal.</p><button type="button" class="ghost-button compact">Manage Settings</button></div></article>
            <article class="panel info-card"><div class="info-icon soft-orange"><svg viewBox="0 0 24 24"><rect x="5" y="6.5" width="14" height="12" rx="2"/><path d="M8 4.5v4"/><path d="M16 4.5v4"/><path d="M5 10h14"/></svg></div><div class="info-copy"><h2>Payment Method</h2><p>Visa ending in 4242<br>Expires 04/27</p><button type="button" class="ghost-button compact">Update Payment Method</button></div></article>
            <article class="panel info-card"><div class="info-icon soft-green"><svg viewBox="0 0 24 24"><path d="M7 10.5a5 5 0 0 1 10 0v1.5a2 2 0 0 1-2 2h-1l-2.2 2.2a1 1 0 0 1-1.7-.7V14H9a2 2 0 0 1-2-2Z"/><path d="M9.5 9.5h.01"/><path d="M14.5 9.5h.01"/></svg></div><div class="info-copy"><h2>Need Help?</h2><p>If you have any questions about your subscriptions, our support team is here to help.</p><button type="button" class="ghost-button compact">Contact Support</button></div></article>
        </section>
    </div>
</x-filament-panels::page>
